version: 2.1
orbs:
  pulumi: pulumi/pulumi@2.0.0
jobs:
  build:
    docker:
      - image: circleci/node:11
    working_directory: ~/repo
    steps:
      - checkout
      - pulumi/login
      - run:
          working_directory: ~/repo/pulumiProject
          command: |
            npm install
            npm install @types/mime
      - pulumi/update:
          working_directory: ~/repo/pulumiProject
          stack: hml
          skip-preview: true
