version: 2.1
orbs:
  pulumi: pulumi/pulumi@2.0.0
jobs:
  deploy_dev:
    docker:
      - image: circleci/node:11
    working_directory: ~/repo
    steps:
      - checkout
      - pulumi/login
      - run:
          working_directory: ~/repo/pulumiProject
          command: |
            npm install
            npm install @types/mime
      - run:
          name: Set AWS keys
          command: |
            export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - pulumi/update:
          working_directory: ~/repo/pulumiProject
          stack: dev
          skip-preview: true

  deploy_hml:
    docker:
      - image: circleci/node:11
    working_directory: ~/repo
    steps:
      - checkout
      - pulumi/login
      - run:
          working_directory: ~/repo/pulumiProject
          command: |
            npm install
            npm install @types/mime
      - run:
          name: Set AWS keys
          command: |
            export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - pulumi/update:
          working_directory: ~/repo/pulumiProject
          stack: hml
          skip-preview: true

  deploy_prd:
    docker:
      - image: circleci/node:11
    working_directory: ~/repo
    steps:
      - checkout
      - pulumi/login
      - run:
          working_directory: ~/repo/pulumiProject
          command: |
            npm install
            npm install @types/mime
      - run:
          name: Set AWS keys
          command: |
            export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - pulumi/update:
          working_directory: ~/repo/pulumiProject
          stack: prd
          skip-preview: true

workflows:
  version: 2
  deploy_stacks:
    jobs:
      - deploy_dev
      - deploy_hml:
        requires:
          - deploy_dev
      - hold:
        type: approval
        requires:
          - deploy_hml
      - deploy_prd:
        requires:
          - hold
