version: 2.1
orbs:
  pulumi: pulumi/pulumi@2.0.0
jobs:
  build:
    docker:
      - image: circleci/node:11
    working_directory: ~/repo
    steps:
      - checkout
      - pulumi/login
      - run:
          working_directory: ~/repo/pulumiProject
          command: |
            npm install
            npm install @types/mime
      - run:
            name: Configure AWS Access Key ID
            command: |
              aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID} --profile default
      - run:
          name: Configure AWS Secret Access Key
          command: |
            aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY} --profile default
      - pulumi/update:
          working_directory: ~/repo/pulumiProject
          stack: hml
          skip-preview: true
